### ISSUE TITLE
Problem with Installing Betse 1.4.1

### ISSUE THREAD

**Issue by dcliner77** [betsee/betse#5]
Hi there,

I'm having trouble with installing and running betse 1.4.1. I think it has something to do with the version of python on my WSL (3.10), but I can't figure out how to use a >=3.11. I used the pip install --upgrade betse. Then it installs betse 1.3.0. When i try using betse, i get import errors and it exits. If it is an issue with the python version on wsl, I am not sure how to update it to a later version. 

thanks in advance for your help!

-Dillon

**Comment by leycec** [comment]
**Ah-ha!** More installation woes, huh? Python packaging is indeed a thing – a very sucky thing. :face_exhaling: 

We'll get you squared away with a working BETSE 1.4.1 installation straight away. It's likely that you're experiencing a classic **dependency conflict**. `pip` is silently refusing to upgrade you from BETSE 1.3.0 to BETSE 1.4.1. Why? Because `pip` is dumb. BETSE 1.4.1 requires *incredibly* new versions of the **standard Python scientific stack** (like NumPy, SciPy, and Matplotlib) that are conflicting with one of the other Python packages you've already installed with `pip`.

Thankfully, fixing this on your end is super easy. Just...

## Start Over from Scratch with a New Python Environment

Your existing `pip` environment is cursed beyond redemption. Deleting (or simply ignoring) your existing `pip` environment and creating a new `pip` environment specific to BETSE 1.4.1 is the solution. Thankfully, deleting `pip` environments is basically harmless. They just have old Python packages installed in them. So what, right? Nobody wanted those old packages, anyway. Nothing is lost by deleting them locally. You can always reinstall them later if need be.

Let's walk through a standard `pip` workflow to get an idea of how these environments work:

```bash
# Let's create a new Python environment just for BETSE 1.4.1.
# This environment will now live at the "betse141/" subdirectory
# under your home directory. The "~" is an alias for your home
# directory on Linux -- and thus WSL, too. Anyway! Movin' on.
$ python -m venv ~/betse141

# Great! Let's activate this new environment.
$ source ~/betse141/bin/activate

# Great! Let's install BETSE 1.4.1 into this environment.
(betse141) $ python -m pip install betse==1.4.1
Collecting betse==1.4.1
  ...
```

Possibly still good? If you're *still* not receiving joy, Anaconda is also a valid option that might yield more joy. Please see [this Anaconda-friendly writeup I recently wrote for another BETSE user](https://github.com/betsee/betse/issues/4#issuecomment-2380397859).

Something's gotta work. I swear that BETSE 1.4.1 will work for you someday. :smiling_face_with_tear:

**Comment by dcliner77** [comment]
Hi there, 

Thanks so much for your response! I tried the above and no luck! So instead, I decided to go the good ole reptile route (anaconda3). I followed the steps from the anaconda-friendly write up, and now I have a betse141 environment. However, whenever I use betse try, it gives this message again, 

[betse] Welcome to <<BETSE 1.3.0 | CPython 3.10.12 | Ubuntu 22.04.5>>.
[betse] Loading third-party dependencies...
[betse] Exiting prematurely due to fatal error:

ImportError: cannot import name 'register_cmap' from 'matplotlib.cm' (/home/dcliner7/.local/lib/python3.10/site-packages/matplotlib/cm.py)

Traceback (most recent call last):
  File "/home/dcliner7/.local/lib/python3.10/site-packages/betse/util/cli/cliabc.py", line 173, in run
    self._init_app_libs()
  File "/home/dcliner7/.local/lib/python3.10/site-packages/betse/util/cli/cliabc.py", line 673, in _init_app_libs
    app_meta.init_libs(matplotlib_backend_name=matplotlib_backend_name)
  File "<string>", line 14, in __init_libs_type_checked__
  File "/home/dcliner7/.local/lib/python3.10/site-packages/betse/util/app/meta/appmetaabc.py", line 262, in init_libs
    mpl_config.init(backend_name=matplotlib_backend_name)
  File "/home/dcliner7/.local/lib/python3.10/site-packages/betse/lib/matplotlib/matplotlibs.py", line 174, in init
    from betse.lib.matplotlib import mplcolormap
  File "/home/dcliner7/.local/lib/python3.10/site-packages/betse/lib/matplotlib/mplcolormap.py", line 26, in <module>
    from matplotlib.cm import (

many fingers clicking
screens are full of letters
what is their meaning?

This was after I activated the betse141 environment. I'll get it someday!

**Comment by dcliner77** [comment]
Great news! I got it to work. Now on to tutorial projects?

**Comment by leycec** [comment]
**Wondrous news!** I'm so glad you were able to resolve everything. Yes, let's see. What now, huh? Generally speaking, your first point of entry into the wide world of BETSE should *usually* be...

## `betse try`: The 500lb Bioelectric Gorilla in the Room

Have you tried running the `betse try` command yet? Just copy-paste this into your terminal:

```bash
betse try
```

Does `betse try` display an animated simulation for you? If so, great. If not, not so great. `betse try` simulates the bioelectric consequences of a "wound" (i.e., of removing a group of adjacent cells from a biological tissue).

If `betse try` worked as advertised, try taking a peek inside the `sample_sim/sample_sim.yaml` file the `betse try` command automatically generated on your behalf. This file configures the bioelectric simulation that the `betse try` command then simulates. There's a *lot* of fun stuff to play around with in that file. For example, you might try:

* Increasing the duration of the simulation via the `sim time settings/total time` option to see what happens over the course of, say, a full minute or even hour.
* Increasing the number of simulated cells via the `world options/world size` option to see what happens to a larger tissue cluster – maybe even a *much* larger tissue cluster.
* Simulating a different set of ions via the `general options/ion profile` option to see, say, how an amphibious *Xenopus* tissue responds to a wound event.

Relatedly...

## BETSE 1.0 Documentation: Still the Best We've Got

Have you had a chance to skim through [our official BETSE 1.0 documentation](https://www.dropbox.com/scl/fi/jz7gouf9709ompvd9oah0/BETSE_Documentation_April10th2019.pdf?rlkey=4k2ks0d2n0723g2vums7o13dk&e=1&dl=0)? This is an *excellent* PDF-formatted write-up of everything BETSE has to offer. And don't let the "1.0" deter you! It's all still relevant and, honestly, the best we've got.

Let's ping @pietakio (i.e., Dr. Alexis Pietak – also known as my beautiful wife). Do we have any tutorial projects lying about for our good friend @dcliner77 *or* is [the BETSE 1.0 documentation](https://www.dropbox.com/scl/fi/jz7gouf9709ompvd9oah0/BETSE_Documentation_April10th2019.pdf?rlkey=4k2ks0d2n0723g2vums7o13dk&e=1&dl=0) still the best bet there, @pietakio? :thinking:

**Comment by pietakio** [comment]
Hi @dcliner77,

The documentation pdf is the best place to start…

Then we have a number of tutorials that are based on examples taken from our published papers and can be found here:

https://github.com/betsee/betse/blob/main/doc/md/TUTORIALS.md

These were developed in 2018 and have not been recently tested but hopefully still work. The project yaml files are heavily commented to assist in understanding. 

Hope that helps,

Alexis

**Comment by dcliner77** [comment]
Thank you so much @pietakio and @leycec for the assistance and guidance! I successfully ran the betse try command. I've started by reading the documentation and the config file, as well as the results of the test simulation. It is very interesting and I look forward to learning more.

Is it currently possible to use betse to simulate the application of an electric field to a single cell within a cell cluster? I am interested in how bioelectric fields may instruct cells to proliferate, differentiate, or navigate in a tissue environment. I thought maybe one way to probe cell behavior and communication of cells could be to apply an external electric field to a single cell within a cell cluster and see how signals propagate? If that makes any sense. Feel free to correct my way of thinking, as I am not in any way an expert or very knowledgeable on the subject. I'm just shuffling around in the dark, hoping to find a light. 

Also, would you have any advice for someone who may want to become a 'developer' of software like betse? I am not very knowledgeable and would be starting from the ground up, besides some familiarity with python (thanks to a computer science course i took years ago).

thanks again for all your help,

Dillon

**Comment by leycec** [comment]
> Also, would you have any advice for someone who may want to become a 'developer' of software like betse?

**Yes! Yes!** So much yes! The first action item for you would to become familiar with `git` (in general) and GitHub (specifically). Try this workflow to get started:

1. **Fork this repository on GitHub.** Click the "Fork" button on the upper right-hand corner of this GitHub repository. You should now be at a URL in your browser that reads something like `https://github.com/dcliner77/betse`. Are you there? Excellent. Let's proceed.
2. **Get the SSH URL of your new fork.** Thankfully, this is easy:
   1. Click the "Code" drop-down on the upper right-hand corner of your GitHub fork. 
   2. Click the "SSH" tab.
   3. Copy-paste the URL that GitHub shows in the edit box. It should look something like `git@github.com:dcliner77/betse.git`. Do you see that? Great!
3. **Clone your new fork to your local machine.** Open up a Linux terminal and do something like this:

   ```bash
   mkdir ~/python  # <-- make a new directory for Python development
   cd ~/python     # <-- change to this new directory
   git clone git@github.com:dcliner77/betse.git  # <-- clone your new fork to a new "~/python/betse/" subdirectory
   cd betse        # <-- change to this new "~/python/betse/" subdirectory
   ```

4. **Uninstall your existing version of BETSE to avoid complications.** I think you're on Anaconda still, right? If so, you'll want to do something like this:

   ```bash
   conda uninstall betse
   ```

5. **Reinstall your forked local copy of BETSE.** In the Python world, you install a local copy of a package that you're actively hacking on in so-called "editable mode." Interestingly, the best way to install an "editable" package in `conda` is to use... `pip`!? Weird but true. Let's do this:

   ```bash
   cd ~/python/betse  # <-- make sure you're in the right directory!
   pip install -e .   # <-- install BETSE "editably"
   ```

6. **Try running `betse` and make sure everything still works.** The `betse` command should still behave as expected: e.g.,

   ```bash
   betse
   ```

## Uhh... What Now!? This Is So Scary.

If all of *that* worked, you're good to now begin hacking on BETSE itself. :partying_face: 

First, how do you actually hack on Python code? To preserve your sanity, you probably want to use either Microsoft Visual Studio Code (VSCode) *or* JetBrains PyCharm Community Edition as your Python integrated development environment (IDE). If you're currently using something else, I'd advise learning one or the other of VSCode or PyCharm. They're both free ("as in beer") and equally excellent for Python development.

Whichever you choose, go ahead and add `~/python/betse` as a new Python project in your IDE. Whenever you hack on the BETSE codebase, just package your changes as a new `git` commit and push those changes to your GitHub BETSE fork. If your changes are *really* awesome and you think a wider audience might benefit from those changes, please do feel free to submit those changes as a GitHub Pull Request (PR) to this main BETSE repository.

I'd be delighted to help you with all that as needed. But that's sorta the "10 Minute BETSE Development from Hell" primer. :smile_cat: 

It kinda seems like this specific issue has been addressed. So... let's close her out, boys! Thanks again for choosing BETSE. Have a great Autumn, @dcliner77. May the bioelectricity be with you.
